language: python
python:
  - "3.9"
  - "3.10-dev"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
script:
  - pytest --cov=src --cov-report= --durations=0
after_success:
  - codecov
