#!/usr/bin/env bash

echo "Running pre-push hook"

rm coverage.xml
codecov --token="310aba3a-4a04-49cb-a516-7444866cac1c"

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Pre-push must pass before pushing!"
 exit 1
fi
