name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install --system mypy pytest pytest-cov
        uv pip install --system -r requirements.txt
    - name: mypy
      run: |
        mypy --install-types --non-interactive .
    - name: pytest
      run: |
        pytest --cov=wolfbot --cov-report= --durations=0
    - name: codecov
      uses: codecov/codecov-action@v1
